### ISSUE TITLE
0.33版本在杂交版2.2中自由放置功能失效

### ISSUE THREAD

**Issue by 2915841032** [EFrostBlade/PVZHybrid_Editor#12]
0.33版本和0.32版本在杂交版2.2中自由放置功能失效,但是,0.31版本的自由放置可以使用,是不是修改了自由放置的代码嘞?
还有修改植物卡槽,植物不对版,,请求作者大大修复一下,作者大大加油

**Comment by EFrostBlade** [comment]
win7版好像是用不了
